services:
  kafka:
    image: apache/kafka:3.7.1
    container_name: kafka
    hostname: kafka
    restart: unless-stopped
    user: "0:0"
    ports:
      - "29092:29092"
    expose:
      - "9092"
    environment:
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_LOG_DIRS: "/kafka/data"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKAJS_NO_PARTITIONER_WARNING: "1"
    volumes:
      - kafka_data:/kafka/data
    healthcheck:
      test:
        - CMD-SHELL
        - /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1 || exit 1
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s

  kafka-init:
    image: apache/kafka:3.7.1
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic user.get.all --partitions 1 --replication-factor 1 &&
       /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic user.get.all.reply --partitions 1 --replication-factor 1"


  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: nest-producer
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    volumes:
      - ./producer:/app
      - /app/node_modules
    ports:
      - 3001:3001

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: nest-consumer
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    volumes:
      - ./consumer:/app
      - /app/node_modules
    expose:
      - "3000"

volumes:
  kafka_data:
